name: Building Master
on:
  push:

jobs:
  setup:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checking out repository
      uses: actions/checkout@v5

    - name: Install dependencies for Nitrox
      run: dotnet restore

  build:
    needs: setup
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Build
      run: dotnet build Nitrox.sln -c ${{ matrix.configuration }} --no-restore

