name: Building Nitrox

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dockerize
      uses: zcong1993/setup-dockerize@v1.2.0
    - name: Setup steamCMD
      run: docker run -it --name=steamcmd cm2network/steamcmd bash
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore Nitrox.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild Nitrox.sln -p:Configuration=Release
